server:
  port: 8000

spring:
  application:
    name: easy-im-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easy_im?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true
    username: root
    password: root
  redis:
    database: 10
    host: localhost
    port: 6379
    timeout: 5000

minio:
  endpoint: http://127.0.0.1:9000
  fileHost: http://127.0.0.1:9000
  bucketName: easy-im
  accessKey: root
  secretKey: rootroot
  imgSize: 1024
  fileSize: 1024