server:
  port: 8000

spring:
  application:
    name: easy-im-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18375
    gateway:
      httpclient:
        connect-timeout: 60000
        response-timeout: 60000
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:10010"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "PATCH"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 36000
      routes:
        # 登录认证服务
        - id: easy-im-auth
          uri: lb://easy-im-auth
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AddRequestHeader=X-Request-Source, easy-im-gateway
            - AddResponseHeader=X-Response-Source, easy-im-gateway